global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'localhost:9090'


  - job_name: 'petshop'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "petshop:3000"

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - "node-exporter:9100"